name: botchaban
on:
  #schedule:
   # - cron: '14 9/8 * * *'  # trigger at 09:14 and 17:14 every day
  push:
    branches:
      -master
jobs:
  botchaban-post:
    runs-on: macOS-latest
    env:
      BOT_CHABAN_TWITTER_CONSUMER_API_KEY: ${{ secrets.BOT_CHABAN_TWITTER_CONSUMER_API_KEY }}
      BOT_CHABAN_TWITTER_CONSUMER_API_SECRET: ${{ secrets.BOT_CHABAN_TWITTER_CONSUMER_API_SECRET }}
      BOT_CHABAN_TWITTER_ACCESS_TOKEN: ${{ secrets.BOT_CHABAN_TWITTER_ACCESS_TOKEN }}
      BOT_CHABAN_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.BOT_CHABAN_TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install glue package
        run: Rscript -e 'install.packages("glue", dependencies = TRUE)'
      - name: Install jsonlite package
        run: Rscript -e 'install.packages("jsonlite", dependencies = TRUE)'
      - name: Install tibble package
        run: Rscript -e 'install.packages("tibble", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install tidyr package
        run: Rscript -e 'install.packages("tidyr", dependencies = TRUE)'
      - name: Install lubridate package
        run: Rscript -e 'install.packages("lubridate", dependencies = TRUE)'
      - name: Install devtools package
        run: Rscript -e 'install.packages("devtools", dependencies = TRUE)'
      - name: Install devtools package
        run: Rscript -e 'devtools::install_github("hadley/emo")'
      - name: Create and post tweet
        run: Rscript botchaban.R
